# Dockerfile untuk Aplikasi Laravel

# --- Tahap 1: Base Image & PHP Dependencies ---
# Kita mulai dari gambar dasar resmi PHP dengan Composer
FROM composer:2 as vendor

WORKDIR /app
COPY database/ database/
COPY composer.json composer.lock ./
# Install semua dependensi composer
RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist


# --- Tahap 2: Setup Aplikasi Utama ---
# Kita gunakan gambar PHP-FPM dengan Nginx untuk web server
FROM webdevops/php-nginx:8.2-alpine

# Set variabel lingkungan yang dibutuhkan oleh image dasar ini
ENV WEB_DOCUMENT_ROOT /app/public
ENV APP_ENV production
ENV LOG_CHANNEL stderr

# Salin file-file aplikasi Anda
COPY . /app

# Salin dependensi yang sudah di-install dari tahap sebelumnya
COPY --from=vendor /app/vendor/ /app/vendor/

# Atur kepemilikan file agar web server bisa menulis ke folder storage dan bootstrap/cache
RUN chown -R application:application /app/storage /app/bootstrap/cache

# Di Render, kita tidak perlu mengekspos port secara manual
# Aplikasi akan berjalan di port internal yang disediakan Render

CMD ["/usr/local/bin/runner"]